name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Check-out du dépôt
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Installer Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Vous pouvez choisir la version de Python que vous utilisez
    
    # Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Exécuter les tests avec pytest
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
    
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to production (simulated)
      run: |
        echo "Déploiement réussi !"